### ISSUE TITLE
Folder node selected only support

### ISSUE THREAD

**Issue by luqin** [MandarinConLaBarba/react-tree-menu#10]
![image](https://cloud.githubusercontent.com/assets/2267688/8537553/31914612-2493-11e5-857f-789b870f665e.png)

**Comment by MandarinConLaBarba** [comment]
This could be done by handling the event to your liking, I think. Or perhaps I don't understand the feature exactly?

**Comment by MandarinConLaBarba** [comment]
Closing, please re-open if this is still something you'd like to discuss.
