### ISSUE TITLE
UI not rendering properly 

### ISSUE THREAD

**Issue by dianadkle** [MandarinConLaBarba/react-tree-menu#13]
I am trying to use this boilerplate (https://github.com/christianalfoni/react-app-boilerplate) to load your tree menu.  The UI is not rendering properly, but it seems like the actual event listeners are working.  Clicking on the various menu items causes the text to change from "Waiting for interaction" to "Event Received."  How can I get the UI to look like the example? 

<img width="1413" alt="screen shot 2015-08-11 at 11 18 39 am" src="https://cloud.githubusercontent.com/assets/9128611/9206162/103477a2-401b-11e5-857a-901ec59df013.png">

**Comment by MandarinConLaBarba** [comment]
Just getting around to this...if you can throw up a gh repo/fork somewhere I'll be glad to download and check it out..

**Comment by MandarinConLaBarba** [comment]
Closing, please re-open if you're able to provide a fork I can use to test your circumstances.
