### ISSUE TITLE
Compatible with React 0.14

### ISSUE THREAD

**Issue by gregorym** [MandarinConLaBarba/react-tree-menu#15]
I get the following error message:

```
Uncaught Error: Invariant Violation: TreeMenu.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

**Comment by MandarinConLaBarba** [comment]
@gregorym thanks for bringing this to my attention. 

I've created a branch `react-0.14`....let me know how that works for you. I can't produce your specific error. This branch bundles fine w/ `react` + `react-dom` and the examples all work. The console is also free of any deprecation warnings.

https://github.com/MandarinConLaBarba/react-tree-menu/tree/react-0.14

**Comment by gregorym** [comment]
Cool! 
I'll give it a try and let you know.

**Comment by gregorym** [comment]
[Edit: NVM, my error comes from somewhere else]

I  am able to reproduce using the data props.

```
data = { label: 'test'};

<div className={classes.join(' ')}>
        <TreeMenu data={data} />
      </div>
```

**Comment by shoflo-staging** [comment]
Ok thanks

**Comment by MandarinConLaBarba** [comment]
Ok thanks
