### ISSUE TITLE
Setting collapsed: true in data breaks stateful tree-menu

### ISSUE THREAD

**Issue by adailey14** [MandarinConLaBarba/react-tree-menu#17]
I am setting collapsed true in the initial data array. When I render the component I am unable to expand the node. Without setting collapsed true I can expand and collapse as expected.

```
data= [
  {label: 'node1', collapsed: true, children: [
    {label: 'node2'},
    {label: 'node3'},
  ]}
]

<div>
  <TreeMenu
    stateful={true}
    onTreeNodeClick={onTreeNodeClick}
    onTreeNodeCollapseChange={onTreeNodeCollapseChange}
    onTreeNodeCheckChange={onTreeNodeCheckChange}
    expandIconClass="fa fa-chevron-right"
    collapseIconClass="fa fa-chevron-down"
    data={data} />
</div>
```

I suspect the stateful collapsed variable is being overwritten by the props collapsed variable in tree_node but couldn't quite figure it out from glancing at the project code.

(Sorry I was signed in as the wrong github user when I first posted this issue!)

**Comment by MandarinConLaBarba** [comment]
@adailey14 this should be fixed in most recent version - please let me know if that doesn't work for you.
